# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt test

    - name: Git checkout (merge)
      uses: actions/checkout@v3
      if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0

    - name: Git checkout (PR)
      uses: actions/checkout@v3
      if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

    - name: Run tests
      run: sbt clean coverage test

    - name: Upload coverage data to Coveralls
      run: sbt coverageReport coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}

